### ISSUE TITLE
Over Data Quota

### ISSUE THREAD

**Issue by ammiiamm** [cstorm125/thai2fit#1]
Hello, 

I tried to `git lfs clone` this repository for checking Thai2vec.vec but I got the error about the data quota of this repository as follow:

> git lfs clone https://github.com/cstorm125/thai2vec.git
Cloning into 'thai2vec'...
remote: Counting objects: 68, done.
remote: Total 68 (delta 0), reused 0 (delta 0), pack-reused 68
Unpacking objects: 100% (68/68), done.
Git LFS: (0 of 8 files) 0 B / 706.32 MB                                                                
batch response: This repository is over its data quota. Purchase more data packs to restore access.

can you please share the large size files via other sources?

**Comment by cstorm125** [comment]
Thanks for the report. I've upgraded the data pack for lfs and you should be able to download it now. Considering changing the storage to other sources.

**Comment by cstorm125** [comment]
Google drive link: https://drive.google.com/drive/folders/1_vZr_iR_LqIX4rEi7i5spN_6QDgj5r81?usp=sharing

**Comment by ammiiamm** [comment]
Thank you so much na ka'
