### ISSUE TITLE
Possible improvements

### ISSUE THREAD

**Issue by titipata** [cstorm125/thai2fit#3]
Hi krub P' Charin, 

I just have few suggestions that might make the library easier to use:
- Make it a libraries with `load_model` function so we can do `from thai2vec import load_model` which can load trained vector directly. It would be even better if we can also have word vector in binary format e.g. `thai2vec.bin` which can be loaded using `fastText` library.
- It would be great to if you can add how you tokenize and clean the text in `README.md` i.e. using which libraries to tokenizer Thai text or how you replace digits. -- (I just saw that you use `pythainlp`, NVM!)
- Multiple dimensions > `100d`, `300d`?

**Comment by cstorm125** [comment]
Hi titipata. 

Thanks for some great suggestions! I'm in the process of refactoring the library as we speak and once it's done most of the stuff you mention should be there and in pyThaiNLP itself.

1. The word-vector side of thai2vec has already been integrated to pyThaiNLP and I think it allows you to do something like load_model.

2. Binary format is a great idea. I will add it when I finish refactoring or if you can create and send it over that'd be great too.

3. Not entirely sure if it's a good idea. I would need to try seeing the effect of dimension reduction such as PCA and LDA vs smaller vector size. Again great project to try.

**Comment by titipata** [comment]
That's awesome to hear! I can also help with some refactoring (later).

For multiple dimensions, I was thinking about 100d cause it's very handy to use in variety of small projects. For example, in English, typically, people will start prototyping the project using Glove 6B, 100 dimensions before 300d. However, I totally agree that it might not be as good as using 300d when we see the projections in 2D.
