### ISSUE TITLE
Preprocessing code missing from the LSTM notebook

### ISSUE THREAD

**Issue by p16i** [cstorm125/thai2fit#8]
<img width="951" alt="image" src="https://user-images.githubusercontent.com/1214890/51942346-1f54a700-2417-11e9-9554-0a9589218f50.png">

It seems `ThaiTokenizer` and `thai_rules` aren't defined in the [notebook][1]. 

[1]: https://github.com/cstorm125/thai2fit/blob/1b67ba6e53312c7cf245909b50c28606aee4a50d/notebook/lstm_wongnai.ipynb

**Comment by cstorm125** [comment]
They aee part of pythainlp.ulmfit
